export type View =
  | 'HOME'
  | 'COMMUNITY'
  | 'POST_DETAIL'
  | 'GAME_DETAIL'
  | 'PROFILE'
  | 'ORDER_CONFIRM'
  | 'LEGEND_LIST'
  | 'ALL_REVIEWS'
  | 'CATEGORY_SERVICES'
  | 'IM'
  | 'IM_DETAIL'
  | 'NOTIFICATIONS'
  | 'CONTACTS'
  | 'COMMUNITY_SELECTOR'
  | 'ME'
  | 'WALLET'
  | 'RECHARGE'
  | 'WITHDRAW'
  | 'APPLY_PLAYER'
  | 'APPLY_PLAYER_CATEGORY'
  | 'APPLY_PLAYER_DETAILS'
  | 'PLAYER_PROFILE_EDIT'
  | 'SETTINGS'
  | 'MY_ORDERS'
  | 'SETTINGS_EDIT_PROFILE'
  | 'SETTINGS_CHANGE_PASSWORD'
  | 'SETTINGS_LINKED_ACCOUNTS'
  | 'SETTINGS_LANGUAGE'
  | 'SETTINGS_PRIVACY'
  | 'SETTINGS_TERMS';

export const BUSINESS_TOKEN_KEY = 'business_workbench_token';
export const BUSINESS_UI_AUTH_KEY = 'business_ui_authenticated';

export const PROTECTED_VIEWS = new Set<View>([
  'ORDER_CONFIRM',
  'IM',
  'IM_DETAIL',
  'NOTIFICATIONS',
  'CONTACTS',
  'WALLET',
  'RECHARGE',
  'WITHDRAW',
  'APPLY_PLAYER',
  'APPLY_PLAYER_CATEGORY',
  'APPLY_PLAYER_DETAILS',
  'PLAYER_PROFILE_EDIT',
  'SETTINGS',
  'MY_ORDERS',
  'SETTINGS_EDIT_PROFILE',
  'SETTINGS_CHANGE_PASSWORD',
  'SETTINGS_LINKED_ACCOUNTS',
  'SETTINGS_LANGUAGE',
  'SETTINGS_PRIVACY',
  'SETTINGS_TERMS',
]);
